pipeline {
    agent {
        kubernetes {
            cloud 'eks-build-my-app'
            inheritFrom 'build-agent'
        }
    }

    environment {
        ECR_REGISTRY = "748624204530.dkr.ecr.ap-south-1.amazonaws.com"
        ECR_REPO     = "my-app"
        IMAGE_TAG    = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                container('git') {
                    git branch: 'main',
                        url: 'https://github.com/arupsscet1-buff/google-online-boutique.git',
                        credentialsId: 'github-creds'
                }
            }
        }

        stage('Secret Scan') {
            steps {
                container('gitleaks') {
                    sh 'gitleaks detect --source . --no-git -v --exit-code 1'
                }
            }
        }

        stage('Detect Changed Services') {
            steps {
                container('git') {
                    script {

                        env.CHANGED_SERVICES = sh(
                            script: '''
                            git diff --name-only origin/main...HEAD \
                            | grep '^src/' \
                            | cut -d/ -f2 \
                            | sort -u
                            ''',
                            returnStdout: true
                        ).trim()

                        echo "Changed Services:"
                        echo env.CHANGED_SERVICES
                    }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                container('sonar') {
                    withSonarQubeEnv('sonarqube-server') {
                        sh '''
                            sonar-scanner \
                            -Dsonar.projectKey=my-app-${SERVICE} \
                            -Dsonar.sources=.
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('Check env variables') {
            steps {
                container('jnlp') {
                    sh '''
                    echo "--- Checking AWS Environment ---"
                    env | grep AWS || echo "AWS Env variables not found in shell path"
                    '''                
                }
            }
        }

        stage('Build & Push All Services') {
            steps {
                container('kaniko') {
                    script {
                            sh """
                                /kaniko/executor \
                                --context=`pwd`/src/frontend \
                                --dockerfile=src/frontend/Dockerfile \
                                --destination=${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG} \
                                --cache=true
                            """
                    }
                }
            }
        }

        stage('Image Scan (Trivy)') {
            steps {
                container('trivy') {
                    sh "trivy image ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
                }
            }
        }
        stage('Deploy to EKS') {
            steps {
                container('helm') {
                    sh """
                    image_path=${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}
                    echo "Deploying image: $image_path to EKS"
                    kubectl apply -f kubernetes_manifests/frontend.yaml
                    """
                }
            }
        }
    }
}